src/RDMG.Web/Controllers/Web/ProfileController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RDMG.Core.Abstractions.Services;
using RDMG.Core.Abstractions.Services.Models;
using RDMG.Web.Models.Profile;
using System;
using System.Threading.Tasks;

namespace RDMG.Web.Controllers.Web;

[Authorize]
public class ProfileController : Controller
{
    private readonly IUserService _userService;
    private readonly ICurrentUserService _currentUserService;
    private readonly IMapper _mapper;
    private readonly ILogger _logger;

    public ProfileController(IUserService userService,
        ICurrentUserService currentUserService,
        IMapper mapper,
        ILogger<ProfileController> logger)
    {
        _userService = userService;
        _currentUserService = currentUserService;
        _mapper = mapper;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var model = await _userService.GetAsync(_currentUserService.GetUserIdAsInt());
        return View(_mapper.Map<ProfileViewModel>(model));
    }


    [HttpGet]
    public IActionResult ChangePassword()
    {
        return View(new ProfileChangePasswordModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ChangePassword(ProfileChangePasswordModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _userService.ChangePasswordAsync(_mapper.Map<ChangePasswordModel>(model));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error changing password.");
                ModelState.AddModelError("", ex.Message);
            }
        }
        return View(model);
    }
}

src/RDMG.Web/Controllers/Web/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RDMG.Core.Abstractions.Services;
using RDMG.Core.Abstractions.Services.Models;
using RDMG.Core.Domain;
using RDMG.Web.Models.User;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace RDMG.Web.Controllers.Web;

[Authorize(Roles = Roles.Admin)]
public class UserController : Controller
{
    private readonly IUserService _userService;
    private readonly IMapper _mapper;
    private readonly ILogger _logger;

    public UserController(IUserService userService, IMapper mapper, ILogger<UserController> logger)
    {
        _userService = userService;
        _mapper = mapper;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var list = await _userService.ListAsync(null);

        return View(new UserListViewModel
        {
            Details = list.Select(_mapper.Map<UserEditViewModel>)
        });
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View(new UserCreateViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(UserCreateViewModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _userService.CreateAsync(_mapper.Map<UserModel>(model));
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating user.");
                ModelState.AddModelError("", ex.Message);
            }
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var model = _mapper.Map<UserEditViewModel>(await _userService.GetAsync(id));
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(UserEditViewModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                var user = new UserModel();
                _mapper.Map(model, user);
                await _userService.UpdateAsync(user);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error editing user.");
                ModelState.AddModelError("", ex.Message);
            }
        }
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _userService.DeleteAsync(id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting user.");
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Restore(int id)
    {
        try
        {
            await _userService.RestoreAsync(id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error restoring user.");
        }
        return RedirectToAction("Index");
    }
}

src/RDMG.Web/Views/Shared/_AjaxScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
</environment>

src/RDMG.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RDMG</title>
    <partial name="_StylesPartial" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@Resources.Common.NavHome</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex ">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity!.IsAuthenticated)
                        {
                            if (User.Claims.Any(c => c.Value == RDMG.Core.Domain.Roles.Admin))
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">@Resources.Common.NavUserManagement </a></li>
                            }
                            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Dungeon" asp-action="Index">@Resources.Common.NavDungeons</a></li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <partial name="_Login" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; @Resources.Common.Copyright - @System.Reflection.Assembly.GetEntryAssembly()?.GetName().Version?.ToString() - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Resources.Common.Privacy</a>
        </div>
    </footer>

    <em class="far fa-arrow-alt-circle-up toparrow" onclick="topFunction()" style="display:none"></em>

    <partial name="_ScriptsPartial" />
    @RenderSection("Scripts", required: false)
</body>
</html>

src/RDMG.Web/Views/Shared/_Login.cshtml
@using RDMG.Web.Helpers
@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="menuProfile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-user fa-fw"></i>
            <span class="">
                @UserHelper.GetUserName(User.Claims)
            </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="menuProfile">
            <a class="dropdown-item" asp-controller="Profile" asp-action="Index">@Resources.Profile.MyProfile</a>
            <a class="dropdown-item" asp-controller="Auth" asp-action="Logout">@Resources.Profile.Logout</a>
        </div>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">@Resources.Profile.Login</a>
    </li>
}

src/RDMG.Web/Views/Shared/_ScriptsPartial.cshtml
<environment include="Development">
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="~/js/password.js"></script>
    <script src="~/js/utils.js"></script>
    <script src="~/js/site.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootbox/bootbox.min.js"></script>
    <script src="~/js/site.min.js"></script>
    <script src="~/js/utils.js"></script>
</environment>

src/RDMG.Web/Views/Shared/_StylesPartial.cshtml
<environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.min.css" type="text/css" />
</environment>
